Increment17
c0dered273/go-adv-metrics pull request #15
Opened 2023-03-09 19:00 UTC by c0dered273

2023-03-12 11:10 UTC, kilchik approved these changes

2023-03-12 11:10 UTC, kilchik commented on internal/config/config.go
> +	Address       = "localhost:8080"              // Адрес сервера
Если ты хочешь, чтобы константы появились в сгенерированной godoc документации, нужно соблюдать те же правила, что и для комментариев к функциям
"The convention is simple: to document a type, variable, constant, function, or even a package, write a regular comment directly preceding its declaration, with no intervening blank line." (https://go.dev/blog/godoc)

2023-03-12 11:10 UTC, kilchik commented on internal/handler/handler_test.go
> +}
Обычно в примере предполагается указать комментарием ожидаемый вывод, так читателю будет понятен результат выполнения кода, для которого ты делаешь пример

2023-03-12 11:11 UTC, kilchik requested changes
Тесты не должны падать, также не увидел, где ты подключил хэндлер для снятия профиля

2023-03-13 19:52 UTC, c0dered273 commented on internal/handler/handler_test.go
> +}
Добавил

2023-03-13 19:52 UTC, c0dered273 commented on internal/config/config.go
> +	Address       = "localhost:8080"              // Адрес сервера
Поправил

2023-03-13 19:55 UTC, c0dered273 commented
> Тесты не должны падать, также не увидел, где ты подключил хэндлер для снятия профиля

Тесты поправил. Pprof подключается через middleware [тут](https://github.com/c0dered273/go-adv-metrics/blob/804ae276393304dec7a6826ce03ab976fc893a40/internal/handler/handler.go#L331)

2023-03-14 16:03 UTC, kilchik approved these changes

2023-03-14 16:13 UTC, merged