Increment3
c0dered273/go-adv-metrics pull request #3
Opened 2022-11-29 16:51 UTC by c0dered273

2022-11-30 19:39 UTC, ASPecherkin requested changes
есть несколько замечаний и одно не критичное

2022-11-30 19:39 UTC, ASPecherkin commented on internal/client/metricclient.go
> +	mu    sync.RWMutex
отлично, рад что сразу используешь sync.RwMutex!

2022-11-30 19:39 UTC, ASPecherkin commented on internal/metric/memmetrics.go
> +var pollCounter int64
здесь это сработает 
но в целом такие общие счетчики , у которых бывает возможность конкуретного обновления из нескольких источников / функций - обычно или оборачивают в sync.RwMutex или используют переменные из пакета atomic ( чуть более сложный вариант)

2022-11-30 19:39 UTC, ASPecherkin commented on internal/storage/memstorage.go
> +	storage = MemStorage{str: make(map[string]metric.Metric)}
лучше не использовать глобальные перменные , а передавать их как зависимость туда , где они необходимы 

второй момент - при инциализации надо проставлять и mutex 
то есть будет как-то так 
```go
storage = MemStorage{
str: make(map[string]metric.Metric),
mx: new(sync.RWMutex),
}
```

2022-12-01 15:36 UTC, c0dered273 commented on internal/metric/memmetrics.go
> +var pollCounter int64
Поправил

2022-12-01 15:39 UTC, c0dered273 commented on internal/storage/memstorage.go
> +	storage = MemStorage{str: make(map[string]metric.Metric)}
Глобальная переменная нигде не используется, в ней просто хранится ссылка на структуру, сама ссылка передается через метод как зависимость. Переписал код более идиоматично. Кроме глобальной переменной других вариантов организации сингтона я не увидел при беглом поиске.

2022-12-01 19:21 UTC, ASPecherkin requested changes
есть серьёзное замечание об использовании глобальной переменной

2022-12-01 19:21 UTC, ASPecherkin commented on internal/storage/memstorage.go
> +var instance *MemStorage
лучше не использовать глобальные переменные
а инциализировать такой storage где-то в main или старте приложения и внедрять его как зависимость там где он необходим 

почему так
иначе не очень очевидно в коде  становится где такой storage используется явно, а где неявно - без передачи как зависимость

2022-12-01 19:21 UTC, ASPecherkin commented on internal/handler/handler.go
> +	"github.com/c0dered273/go-adv-metrics/internal/log"
в go принято группировать импорты
чаще всего используется такая схема разбития 
```go
stdlib

пакеты твоего приложения

пакеты твоей компании

внешние пакеты( github) 

```
обычно достигается это тем, что в IDE подключается использование goimports, а не go fmt для импортов

2022-12-02 10:22 UTC, c0dered273 commented on internal/handler/handler.go
> +	"github.com/c0dered273/go-adv-metrics/internal/log"
Поправил

2022-12-02 10:22 UTC, c0dered273 commented on internal/storage/memstorage.go
> +var instance *MemStorage
Поправил

2022-12-04 14:45 UTC, ASPecherkin approved these changes
принимаю работу

2022-12-04 15:37 UTC, merged